# This is about attributes in array which are NOT rep by(), only methos rep by ()
import numpy as np
myar=np.array([1,2,3,4,5,6])
# print(myar.ndim)
myar1 =np.array([[1,2,3],[4,5,6],[7,8,9]])
print(myar1)
print(myar1.ndim , "Dimension")
print(myar1.size , "Elements")
print(myar1.itemsize , "ITEM-SIZE in BYTES")
print(myar1.shape , "shape of array")
print("Data type of array:-", myar1.dtype)
myar2=myar.reshape(2,3)
print(myar2)
myar3=myar1.reshape(9)
print(myar3)
